# If compiling with ASAN, invoke like this: $ LSAN_OPTIONS=suppressions=lsan.txt 

CXX			= g++
CXXFLAGS	= -O2 -Werror -Wall -Wextra -Wpedantic -std=c++17 \
	-I./include \
	-Wcast-qual \
	-Wno-unused-function -Wno-unused-parameter -Wno-unused-variable \
	-Wno-deprecated-copy \
	-Wno-format-nonliteral \
	-Wformat=2 -Wformat-security \
	-Wnull-dereference -Wstack-protector -Wtrampolines -Wvla \
	-Warray-bounds=2 \
	-Wshift-overflow=2 \
	-Wlogical-op -Wduplicated-cond \
	-Wformat-signedness -Wshadow -Wstrict-overflow=4 \
	-Wundef -Wswitch-enum \
	-Wstack-usage=10000 \
	-D_FORTIFY_SOURCE=2 \
	-fstack-protector-strong \
	-fPIE -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -Wl,-z,separate-code	

LDSANFLAGS = -fsanitize=address \
	-fsanitize=leak \
	-fno-omit-frame-pointer \
	-fsanitize=undefined \
	-fsanitize=bounds-strict \
	-fsanitize=float-divide-by-zero \
	-fsanitize=float-cast-overflow \
	-fanalyzer

LDFLAGS		= -g3 
LDLIBS		= -lm -lmosquittopp 

CXXFLAGS += $(shell wx-config --cppflags)

DOC			= doc
SRC			= src
CPPW		= *.cpp
TARGET     	= wxtest
SRC_FILES 	= $(wildcard $(SRC)/$(CPPW)) $(wildcard$(SRC)/**/$(CPPW))
OBJECTS 	= $(SRC_FILES:%.cpp=%.o)

.SUFFIXES = 

.PHONY: all

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) -o $@ $^ $(LDFLAGS) $(LDLIBS) `wx-config --libs std` $(LDSANFLAGS) 

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ -c $<

.PHONY: doc
doc:
	@doxygen $(DOC)/wxtest.conf

.PHONY: cleandoc
cleandoc:
	@rm -rf $(DOC)/html
	@echo "clean doc done"

.PHONY: clean
clean:
	@rm -rf $(TARGET) $(OBJECTS)
	@echo "clean done"

.PHONY: check
check:
	@cppcheck -I./include \
		--check-config \
		--enable=all \
		--std=c++17 \
		--suppress=missingIncludeSystem \
		$(SRC)	

